---
encoder_n_layers: 3
encoder_d_model: 64
encoder_n_heads: 4
encoder_d_state: 48
encoder_vocab_size: 32000

decoder_n_layers: 3
decoder_d_model: 64
decoder_n_heads: 4
decoder_d_state: 48
decoder_vocab_size: 32000